-- =====================================================
-- V1__create_schema.sql
-- Schema completo da Rick Estética Automotiva
-- Compatível com MySQL 8+
-- AUTO_INCREMENT substitui GENERATED BY DEFAULT AS IDENTITY (padrão SQL:2003
--   suportado por H2/PostgreSQL mas NÃO pelo MySQL 8)
-- LONGTEXT substitui CLOB (tipo padrão SQL não suportado pelo MySQL)
-- Autor: gerado via Flyway baseline — 2026-03-08
-- =====================================================

-- -----------------------------------------------------
-- Tabela: role
-- Entidade de referência para autorizações Spring Security
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS role (
    id   BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(30) NOT NULL UNIQUE
);

-- -----------------------------------------------------
-- Tabela: pessoa
-- Cliente ou funcionário autenticado via JWT
-- Soft-delete: coluna deletado_em
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS pessoa (
    id               BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome             VARCHAR(100),
    cpf              VARCHAR(11) UNIQUE,
    email            VARCHAR(255) NOT NULL UNIQUE,
    telefone         VARCHAR(20),
    data_nascimento  DATE,
    senha            VARCHAR(255),
    deletado_em      TIMESTAMP NULL DEFAULT NULL
);

-- -----------------------------------------------------
-- Tabela: pessoa_roles  (junção N:N)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS pessoa_roles (
    pessoa_id BIGINT NOT NULL,
    role_id   BIGINT NOT NULL,
    PRIMARY KEY (pessoa_id, role_id),
    CONSTRAINT fk_pr_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa (id),
    CONSTRAINT fk_pr_role   FOREIGN KEY (role_id)   REFERENCES role (id)
);

-- -----------------------------------------------------
-- Tabela: categoria
-- Agrupamento de serviços (ex: Lavagem, Polimento)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS categoria (
    id   BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100)
);

-- -----------------------------------------------------
-- Tabela: servico
-- Catálogo de serviços com preço, duração e categoria
-- Soft-delete: coluna deletado_em
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS servico (
    id             BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome           VARCHAR(100) NOT NULL,
    descricao      VARCHAR(255),
    preco          DECIMAL(10, 2) NOT NULL,
    imagem         VARCHAR(512),
    duracao_horas  TIME,
    deletado_em    TIMESTAMP NULL DEFAULT NULL,
    fk_categoria   BIGINT NOT NULL,
    CONSTRAINT fk_servico_categoria FOREIGN KEY (fk_categoria) REFERENCES categoria (id)
);

-- -----------------------------------------------------
-- Tabela: veiculo
-- Veículo do cliente vinculado a ordens de serviço
-- Soft-delete: coluna deletado_em
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS veiculo (
    id          BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    placa       VARCHAR(10),
    modelo      VARCHAR(100),
    marca       VARCHAR(100),
    porte       VARCHAR(50),
    cor         VARCHAR(50),
    ano         VARCHAR(4),
    deletado_em TIMESTAMP NULL DEFAULT NULL,
    fk_usuario  BIGINT,
    CONSTRAINT fk_veiculo_pessoa FOREIGN KEY (fk_usuario) REFERENCES pessoa (id)
);

-- -----------------------------------------------------
-- Tabela: status
-- Estados possíveis de uma OrdemServico
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS status (
    id        BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(50) NOT NULL UNIQUE
);

-- -----------------------------------------------------
-- Tabela: motivo
-- Motivo de cancelamento de uma OrdemServico
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS motivo (
    id        BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(50) NOT NULL UNIQUE
);

-- -----------------------------------------------------
-- Tabela: ordem_servico
-- Ordem gerada a partir do carrinho, com status e agendamento
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ordem_servico (
    id               BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    data_agendamento TIMESTAMP NOT NULL,
    preco_minimo     DECIMAL(10, 2) NOT NULL,
    observacoes      VARCHAR(255),
    dt_conclusao     TIMESTAMP NULL DEFAULT NULL,
    fk_veiculo       BIGINT NOT NULL,
    fk_status        BIGINT NOT NULL,
    fk_motivo        BIGINT,
    CONSTRAINT fk_os_veiculo FOREIGN KEY (fk_veiculo) REFERENCES veiculo (id),
    CONSTRAINT fk_os_status  FOREIGN KEY (fk_status)  REFERENCES status (id),
    CONSTRAINT fk_os_motivo  FOREIGN KEY (fk_motivo)  REFERENCES motivo (id)
);

-- -----------------------------------------------------
-- Tabela: item_servico
-- Item dentro de uma ordem de serviço (snapshot de preço)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS item_servico (
    id               BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    preco            DECIMAL(10, 2) NOT NULL,
    servico_id       BIGINT NOT NULL,
    ordem_servico_id BIGINT NOT NULL,
    CONSTRAINT fk_is_servico       FOREIGN KEY (servico_id)       REFERENCES servico (id),
    CONSTRAINT fk_is_ordem_servico FOREIGN KEY (ordem_servico_id) REFERENCES ordem_servico (id)
);

-- -----------------------------------------------------
-- Tabela: carrinho
-- Seleção temporária de serviços antes de gerar a ordem
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS carrinho (
    id         BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fk_pessoa  BIGINT NOT NULL,
    fk_servico BIGINT NOT NULL,
    CONSTRAINT fk_carrinho_pessoa  FOREIGN KEY (fk_pessoa)  REFERENCES pessoa (id),
    CONSTRAINT fk_carrinho_servico FOREIGN KEY (fk_servico) REFERENCES servico (id)
);

-- -----------------------------------------------------
-- Tabela: favorito
-- Serviços favoritos do cliente
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS favorito (
    id         BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fk_pessoa  BIGINT NOT NULL,
    fk_servico BIGINT NOT NULL,
    CONSTRAINT fk_favorito_pessoa  FOREIGN KEY (fk_pessoa)  REFERENCES pessoa (id),
    CONSTRAINT fk_favorito_servico FOREIGN KEY (fk_servico) REFERENCES servico (id)
);

-- -----------------------------------------------------
-- Tabela: erro_log
-- Auditoria de erros em runtime (persistência assíncrona)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS erro_log (
    id                  BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    timestamp           TIMESTAMP NOT NULL,
    tipo_excecao        VARCHAR(512),
    mensagem            LONGTEXT,
    stack_trace         LONGTEXT,
    endpoint            VARCHAR(1024),
    metodo_http         VARCHAR(10),
    payload_requisicao  LONGTEXT,
    query_params        LONGTEXT,
    headers_requisicao  LONGTEXT,
    usuario_email       VARCHAR(255),
    status_http         INT,
    ambiente            VARCHAR(50),
    ip_cliente          VARCHAR(50),
    user_agent          LONGTEXT
);

-- -----------------------------------------------------
-- Tabela: email
-- Rastreamento de e-mails transacionais enviados
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS email (
    id               BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pessoa_id        BIGINT,
    remetente        VARCHAR(255),
    destinatario     VARCHAR(255),
    com_copia        VARCHAR(255),
    com_copia_oculta VARCHAR(255),
    assunto          VARCHAR(255),
    corpo            LONGTEXT,
    data_envio_email TIMESTAMP NULL DEFAULT NULL,
    status_email     VARCHAR(30),
    CONSTRAINT fk_email_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa (id)
);

